.
# This step ensures that the quagga daemon is running.
- name: ensure quagga is running
  service: name=frr state=started

# The quagga daemons file is a static file that specifies which subdaemons
# are actually running (zebra, bgpd, ospf). This file is not required when
# Quagga is being run using systemd.
- name: configure quagga daemons file
  copy: src=daemons dest=/etc/frr/daemons
  notify:
    - check frr
    - restart frr

# This writes configuration to the Quagga configuration file using the
# information in group_vars/all. The biggest difference between spine and
# leaf configuration are the prefix lists - leafs should only advertise their
# neighboring networks, but spines should advertise any networks they accept.
- name: configure quagga configuration
  template: src=Quagga.conf.j2 dest=/etc/frr/Quagga.conf
  notify:
    - check frr
    - restart frr
